### ISSUE TITLE
Problem with bloom releases

### ISSUE THREAD

**Issue by jacobperron** [OUXT-Polaris/embree_vendor#5]
It looks like there was some issue with the 0.1.0 bloom release into ROS 2 distros. The release build has been disabled for Galactic (https://github.com/ros/rosdistro/pull/30353/) and has been failing for Foxy for a while now https://build.ros2.org/view/Fbin_uF64/job/Fsrc_uF__embree_vendor__ubuntu_focal__source/59

**Comment by hakuturu583** [comment]
Thanks!
